# Generated by Django 3.0.7 on 2020-06-22 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200621_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='productReview',
        ),
    ]
