# Generated by Django 3.0.7 on 2020-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200620_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
