# Generated by Django 3.0.7 on 2020-06-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordermaster_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
    ]
