# Generated by Django 3.0.7 on 2020-06-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200621_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='size',
            new_name='Shoesize',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='size',
            new_name='Shoesize',
        ),
    ]
